-- DROP DATABASE - DELETA UM BANCO
DROP
	DATABASE bercario;

-- CREATE DATABASE - CRIA UM BANCO
CREATE
	DATABASE bercario;

-- USE - UTILIZADO PARA INDICAR EM QUAL BANCO VAI SER CRIADO A TABELA
USE bercario;

-- CREATE TABLE - CRIA UMA TABELA ONDE CADA ITEM DENTRO DOS PARENTESES SÃO UMA COLUNA, TEM QUE ESPECIFICAR O FORMATO DE DADO DA COLUNA
-- PRIMARY KEY - DIZ QUE AQUELE ATRIBUTO É CHAVE PRIMARIA
-- AUTO INCREMENT - DIZ QUE AQUELE ATRIBUTO AUMENTA O NUMERO AUTOMATICAMENTE
-- NOT NULL - DIZ QUE AQUELE ATRIBUTO DEVE SER PREENCHIDO , NÃO PODE ESTAR VAZIO
-- UNIQUE - DIZ QUE SÓ PODE TER UM DAQUELE REGISTRO NA TABELA  
CREATE
	TABLE tb_mae (
		cod_mae INT PRIMARY KEY AUTO_INCREMENT,
        nm_mae VARCHAR(255) NOT NULL,
        tel_mae VARCHAR(20),
        email_mae VARCHAR(255) UNIQUE
);

CREATE
	TABLE tb_medico(
		id_medico INT PRIMARY KEY AUTO_INCREMENT,
        CRM VARCHAR(10) NOT NULL DEFAULT '123456-ES',
        nome_medico VARCHAR(255) NOT NULL
);

-- ALTER - ALTERA ALGO EXISTENTE NO BANCO
-- ADD - ADCIONA COLUNAS A UMA TABELA EXISTENTE
ALTER 
	TABLE tb_medico
		ADD especialidade ENUM("GERAL", "PEDIATRA", "OBSTETRA");

-- PROP COLUMN - DELETA UMA COLUNA EXISTENTE
ALTER 
	TABLE tb_medico
		DROP COLUMN especialidade;

-- MODIFY - MODIFICA UMA COLUNA DE UMA TABELA EXISTENTE
ALTER
	TABLE tb_medico
		MODIFY COLUMN especialidade VARCHAR(20);
	
-- DROP TABLE - DELETA UMA TABELA
DROP
	TABLE tb_medico;

-- CRIA A TABELA BEBE
-- FOREIGN KEY - CRIA UMA CHAVE ESTRANGEIRA PRECISA USAR PARAMETROS PARA LINKAR AS CHAVES
-- REFERENCES - NECESSARIO UTILLIZAR ESTA FUNÇÃO PARA RELACIONAR UMA CHAVE PRIMARIA A UMA CHAVE SECUNDARIA NA TABELA
CREATE
	TABLE 	tb_bebe(
		cod_bebe INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
        nome_bebe VARCHAR(255),
        data_nasc DATE,
        hr_nasc TIME,
        peso DECIMAL(6, 4),
        id_mae INT,
        id_medico INT,
        FOREIGN KEY (id_mae) REFERENCES tb_mae(cod_mae),
        FOREIGN KEY (id_medico) REFERENCES tb_medico(id_medico)
);


    